from enum import Enum
from typing import List, Optional
from pydantic import BaseModel, Field

class RetrievalStrategyType(str, Enum):
    KEYWORD = "KEYWORD"
    SEMANTIC = "SEMANTIC"
    GRAPH = "GRAPH"

class RankingProfileType(str, Enum):
    DEFAULT = "DEFAULT"
    DEFINITION = "DEFINITION"
    TROUBLESHOOTING = "TROUBLESHOOTING"
    COMPLIANCE = "COMPLIANCE"
    FAILURE_ANALYSIS = "FAILURE_ANALYSIS"

class TraversalStrategyType(str, Enum):
    NEIGHBORHOOD = "NEIGHBORHOOD"
    SHORTEST_PATH = "SHORTEST_PATH"
    DEPENDENCY = "DEPENDENCY"
    FAILURE_PROPAGATION = "FAILURE_PROPAGATION"

class QueryComplexityEstimate(BaseModel):
    expected_nodes: int
    expected_edges: int
    expected_cost_ms: int
    expected_tokens: int

class RetrievalPlan(BaseModel):
    """
    Data Transfer Object representing the execution blueprint generated by a Retrieval Planner.
    """
    query: str
    strategies: List[RetrievalStrategyType]
    ranking_profile: RankingProfileType = RankingProfileType.DEFAULT
    budget_tokens: int = Field(default=8000, description="Total budget across all strategies")
    planner_confidence: float = Field(default=1.0, ge=0.0, le=1.0)
    traversal_strategy: Optional[TraversalStrategyType] = None
    estimated_complexity: Optional[QueryComplexityEstimate] = None
    reason: Optional[str] = Field(default=None, description="Explanation of why this plan was chosen")
