"""Add search_vector to document_content

Revision ID: 43a9016c6d1d
Revises: 55653e645061
Create Date: 2026-07-11 13:32:00.666162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '43a9016c6d1d'
down_revision: Union[str, Sequence[str], None] = '55653e645061'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_contents', sa.Column('language', sa.String(), nullable=False))
    op.add_column('document_contents', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.create_index('ix_document_contents_search_vector', 'document_contents', ['search_vector'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_document_contents_search_vector', table_name='document_contents', postgresql_using='gin')
    op.drop_column('document_contents', 'search_vector')
    op.drop_column('document_contents', 'language')
    # ### end Alembic commands ###
