"""add_analytics_columns

Revision ID: b8141a08489c
Revises: d63796cad573
Create Date: 2026-07-16 09:47:53.923913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8141a08489c'
down_revision: Union[str, Sequence[str], None] = 'd63796cad573'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("ALTER TYPE chunkstatus ADD VALUE IF NOT EXISTS 'REEMBED_REQUIRED'")
    op.execute("ALTER TYPE chunkstatus ADD VALUE IF NOT EXISTS 'RETRY_PENDING'")
    op.execute("ALTER TYPE chunkstatus ADD VALUE IF NOT EXISTS 'PROCESSING'")
    sa.Enum('RATE_LIMIT', 'TIMEOUT', 'INVALID_API_KEY', 'INVALID_MODEL', 'NETWORK', 'BUDGET_EXCEEDED', 'CANCELLED', 'UNKNOWN', name='failurereason').create(op.get_bind())
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('failure_reason', sa.Enum('RATE_LIMIT', 'TIMEOUT', 'INVALID_API_KEY', 'INVALID_MODEL', 'NETWORK', 'BUDGET_EXCEEDED', 'CANCELLED', 'UNKNOWN', name='failurereason'), nullable=True))
    op.add_column('document_chunks', sa.Column('processing_ms', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('retry_count', sa.Integer(), nullable=False))
    op.add_column('document_chunks', sa.Column('token_usage', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('estimated_cost', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'estimated_cost')
    op.drop_column('document_chunks', 'token_usage')
    op.drop_column('document_chunks', 'retry_count')
    op.drop_column('document_chunks', 'processing_ms')
    op.drop_column('document_chunks', 'failure_reason')
    # ### end Alembic commands ###
    sa.Enum('RATE_LIMIT', 'TIMEOUT', 'INVALID_API_KEY', 'INVALID_MODEL', 'NETWORK', 'BUDGET_EXCEEDED', 'CANCELLED', 'UNKNOWN', name='failurereason').drop(op.get_bind())
