"""Add telemetry models

Revision ID: ec28a3e9ac42
Revises: 43a9016c6d1d
Create Date: 2026-07-16 08:44:38.957629

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ec28a3e9ac42'
down_revision: Union[str, Sequence[str], None] = '43a9016c6d1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('query', sa.String(), nullable=False),
    sa.Column('retrieval_strategy', sa.String(), nullable=False),
    sa.Column('execution_time_ms', sa.Float(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_search_logs_correlation_id'), 'search_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_search_logs_request_id'), 'search_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_search_logs_user_id'), 'search_logs', ['user_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('request_id', sa.String(), nullable=False),
    sa.Column('correlation_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('document_id', sa.UUID(), nullable=True),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_index(op.f('ix_telemetry_events_correlation_id'), 'telemetry_events', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_document_id'), 'telemetry_events', ['document_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_event_type'), 'telemetry_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_telemetry_events_request_id'), 'telemetry_events', ['request_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_user_id'), 'telemetry_events', ['user_id'], unique=False)
    extraction_status_enum = postgresql.ENUM('PROCESSING', 'EXTRACTED', 'FAILED', 'RETRY_PENDING', name='extractionstatus')
    extraction_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('documents', sa.Column('extraction_status', extraction_status_enum, nullable=True))
    op.create_index(op.f('ix_documents_extraction_status'), 'documents', ['extraction_status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_extraction_status'), table_name='documents')
    op.drop_column('documents', 'extraction_status')
    extraction_status_enum = postgresql.ENUM('PROCESSING', 'EXTRACTED', 'FAILED', 'RETRY_PENDING', name='extractionstatus')
    extraction_status_enum.drop(op.get_bind(), checkfirst=True)
    op.drop_index(op.f('ix_telemetry_events_user_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_request_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_event_type'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_document_id'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_correlation_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_search_logs_user_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_request_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_correlation_id'), table_name='search_logs')
    op.drop_table('search_logs')
    # ### end Alembic commands ###
