"""Add entity and outbox models

Revision ID: f9683c1ed6c4
Revises: 6bb8b359dca1
Create Date: 2026-07-16 11:19:35.733049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f9683c1ed6c4'
down_revision: Union[str, Sequence[str], None] = '6bb8b359dca1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('entities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PENDING_REVIEW', 'MERGED', 'DELETED', name='entitystatus'), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('first_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_document_count', sa.Integer(), nullable=False),
    sa.Column('graph_rank', sa.Float(), nullable=True),
    sa.Column('pagerank', sa.Float(), nullable=True),
    sa.Column('degree', sa.Integer(), nullable=True),
    sa.Column('centrality', sa.Float(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['entities.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entities_canonical_id'), 'entities', ['canonical_id'], unique=False)
    op.create_index(op.f('ix_entities_category'), 'entities', ['category'], unique=False)
    op.create_index(op.f('ix_entities_status'), 'entities', ['status'], unique=False)
    op.create_table('graph_outbox_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.Enum('NODE_UPSERT', 'EDGE_UPSERT', 'NODE_DELETE', 'EDGE_DELETE', name='graphoutboxeventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('graph_projection_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSED', 'FAILED', name='graphoutboxeventstatus'), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_graph_outbox_events_event_type'), 'graph_outbox_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_graph_outbox_events_status'), 'graph_outbox_events', ['status'], unique=False)
    op.create_table('entity_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('canonical_id', sa.UUID(), nullable=False),
    sa.Column('alias_name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['canonical_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_aliases_alias_name'), 'entity_aliases', ['alias_name'], unique=False)
    op.create_index(op.f('ix_entity_aliases_canonical_id'), 'entity_aliases', ['canonical_id'], unique=False)
    op.create_table('entity_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('previous_name', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_entity_versions_entity_id'), 'entity_versions', ['entity_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_entity_versions_entity_id'), table_name='entity_versions')
    op.drop_table('entity_versions')
    op.drop_index(op.f('ix_entity_aliases_canonical_id'), table_name='entity_aliases')
    op.drop_index(op.f('ix_entity_aliases_alias_name'), table_name='entity_aliases')
    op.drop_table('entity_aliases')
    op.drop_index(op.f('ix_graph_outbox_events_status'), table_name='graph_outbox_events')
    op.drop_index(op.f('ix_graph_outbox_events_event_type'), table_name='graph_outbox_events')
    op.drop_table('graph_outbox_events')
    op.drop_index(op.f('ix_entities_status'), table_name='entities')
    op.drop_index(op.f('ix_entities_category'), table_name='entities')
    op.drop_index(op.f('ix_entities_canonical_id'), table_name='entities')
    op.drop_table('entities')
    # ### end Alembic commands ###
