"""Add Relationship models

Revision ID: ff0a0005c5bf
Revises: edcbcef88483
Create Date: 2026-07-16 19:02:01.383024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff0a0005c5bf'
down_revision: Union[str, Sequence[str], None] = 'edcbcef88483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('relationships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('subject_id', sa.UUID(), nullable=False),
    sa.Column('predicate', sa.String(), nullable=False),
    sa.Column('object_id', sa.UUID(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('status', sa.Enum('DISCOVERED', 'PENDING_EVIDENCE', 'ACTIVE', 'SUSPENDED', 'DEPRECATED', 'ARCHIVED', name='relationshipstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['object_id'], ['entities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['entities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'predicate', 'object_id', name='uix_relationship_triple')
    )
    op.create_index(op.f('ix_relationships_object_id'), 'relationships', ['object_id'], unique=False)
    op.create_index(op.f('ix_relationships_predicate'), 'relationships', ['predicate'], unique=False)
    op.create_index(op.f('ix_relationships_status'), 'relationships', ['status'], unique=False)
    op.create_index(op.f('ix_relationships_subject_id'), 'relationships', ['subject_id'], unique=False)
    op.create_table('relationship_evidence',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('relationship_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('supporting_text', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['relationship_id'], ['relationships.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_relationship_evidence_chunk_id'), 'relationship_evidence', ['chunk_id'], unique=False)
    op.create_index(op.f('ix_relationship_evidence_relationship_id'), 'relationship_evidence', ['relationship_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_relationship_evidence_relationship_id'), table_name='relationship_evidence')
    op.drop_index(op.f('ix_relationship_evidence_chunk_id'), table_name='relationship_evidence')
    op.drop_table('relationship_evidence')
    op.drop_index(op.f('ix_relationships_subject_id'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_status'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_predicate'), table_name='relationships')
    op.drop_index(op.f('ix_relationships_object_id'), table_name='relationships')
    op.drop_table('relationships')
    # ### end Alembic commands ###
