"""add_extracted_facts_and_findings

Revision ID: 0d754ef098cf
Revises: aa829a899aa3
Create Date: 2026-07-16 21:34:54.173211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0d754ef098cf'
down_revision: Union[str, Sequence[str], None] = 'aa829a899aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('intelligence_findings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('CONFLICT', 'CORROBORATION', 'DUPLICATE_RECORD', 'MISSING', name='finding_type_enum'), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=False),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('affected_fact_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('asset_id', 'property', 'type', name='uq_asset_property_type')
    )
    op.create_index(op.f('ix_intelligence_findings_asset_id'), 'intelligence_findings', ['asset_id'], unique=False)
    op.create_index(op.f('ix_intelligence_findings_property'), 'intelligence_findings', ['property'], unique=False)
    op.create_table('extracted_facts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('chunk_id', sa.UUID(), nullable=False),
    sa.Column('asset_id', sa.String(), nullable=True),
    sa.Column('property', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=False),
    sa.Column('start_offset', sa.Integer(), nullable=True),
    sa.Column('end_offset', sa.Integer(), nullable=True),
    sa.Column('extraction_model', sa.String(), nullable=False),
    sa.Column('extraction_version', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'STALE', 'ARCHIVED', 'DELETED', name='fact_status_enum'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_extracted_facts_asset_id'), 'extracted_facts', ['asset_id'], unique=False)
    op.create_index(op.f('ix_extracted_facts_property'), 'extracted_facts', ['property'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_extracted_facts_property'), table_name='extracted_facts')
    op.drop_index(op.f('ix_extracted_facts_asset_id'), table_name='extracted_facts')
    op.drop_table('extracted_facts')
    op.drop_index(op.f('ix_intelligence_findings_property'), table_name='intelligence_findings')
    op.drop_index(op.f('ix_intelligence_findings_asset_id'), table_name='intelligence_findings')
    op.drop_table('intelligence_findings')
    # ### end Alembic commands ###
